server:
  port: 8080
spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT-3"
  application:
    name: @project.artifactId@
  datasource:
    url: jdbc:h2:mem:base-api
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
tecnoinfo:
  url-api:
    loja-api: https://hmllojaapi.srv.farmaciassaojoao.com.br
eureka:
  instance:
    ip-address: 10.200.21.250

